# Interpolation syntax
# https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#interpolation-syntax
# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:17.4-bookworm
    #    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 64mb
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-banking}
    ports:
      - "${DB_LOCAL_PORT:-5432}:${DB_DOCKER_PORT:-5432}"
    networks:
      - database

networks:
  database:
    driver: bridge
    name: database